// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMVc7JDFwK5EpEeO4nlopQ04D6lgekM0',
    appId: '1:989297428278:web:34eee7d366d9595ffc9597',
    messagingSenderId: '989297428278',
    projectId: 'singupsinginloginscreen',
    authDomain: 'singupsinginloginscreen.firebaseapp.com',
    storageBucket: 'singupsinginloginscreen.appspot.com',
    measurementId: 'G-D5HHMHNPYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyraUHLNtfcsGtgiPW8kW33VOb9BdSV_M',
    appId: '1:989297428278:android:0bd0dc2d584498e9fc9597',
    messagingSenderId: '989297428278',
    projectId: 'singupsinginloginscreen',
    storageBucket: 'singupsinginloginscreen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMwkIcqnghWfhtBEcstyOt0QAsXC8OI4',
    appId: '1:989297428278:ios:e9b09402ed2f9e2ffc9597',
    messagingSenderId: '989297428278',
    projectId: 'singupsinginloginscreen',
    storageBucket: 'singupsinginloginscreen.appspot.com',
    iosBundleId: 'com.example.singupsinginloginscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMwkIcqnghWfhtBEcstyOt0QAsXC8OI4',
    appId: '1:989297428278:ios:e9b09402ed2f9e2ffc9597',
    messagingSenderId: '989297428278',
    projectId: 'singupsinginloginscreen',
    storageBucket: 'singupsinginloginscreen.appspot.com',
    iosBundleId: 'com.example.singupsinginloginscreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMVc7JDFwK5EpEeO4nlopQ04D6lgekM0',
    appId: '1:989297428278:web:a2e10bc6a7e905b6fc9597',
    messagingSenderId: '989297428278',
    projectId: 'singupsinginloginscreen',
    authDomain: 'singupsinginloginscreen.firebaseapp.com',
    storageBucket: 'singupsinginloginscreen.appspot.com',
    measurementId: 'G-EKW48MYBVF',
  );
}
